# Name of the site (this will show up at the top of your page and in the RSS feed)
name: My Restaurant

# Short description (goes below the title; it will also be used in the RSS feed)
description: We make good food!

# The directory for category index pages. Change it to something else if
# for example you want links like /categories/category1 instead of /category1
category_dir: /categories

# Uncomment if you are planning to run the blog in a subdirectory
# Note - if you enable this, and attempt to view your site locally you have to use the baseurl in your local path.
# Example, you must use http://localhost:4000/path/to/blog
#baseurl: /

# The URL of your actual domain. This will be used to make absolute links in the RSS feed.
url: http://www.myrestaurant.com

# Makes pretty (descriptive) permalinks. See Jekyll docs for alternatives.
permalink: /news/:year/:month/:day/:title/

# Exclude system files
exclude: [.gitignore]

# Control the number of post per page
paginate: 10

# Configure the Asset Bundler
asset_bundler:
  compress:
    js: 'yui'
    css: 'yui'
  markup_templates:
    js: "\t\t<script type=\"text/javascript\" async=\"async\" src=\"{{url}}\"></script>\n"
